services:
  backend:
    build: 
      context: ./backend 
    container_name: az-backend
    restart: always
    ports:
      - "3333:3333"
    networks:
      - app_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: 
      context: ./frontend
    container_name: az-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"  
    networks:
      - app_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  app_network:
    driver: bridge